remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Just learning stuff
description: Writing about whatever I'm learning at the time from making something new to re-imaging a computer. 